language: objective-c

osx_image: xcode7.2

before_script:
  - ./scripts/upstall-swiftlint.sh

script:
- set -o pipefail && xcodebuild -scheme SwiftyTextTable -project SwiftyTextTable.xcodeproj clean build test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
