language: objective-c
osx_image: xcode7.2

env:
  global:
    - FRAMEWORK_NAME=SwiftyTextTable

before_install:
  - ./scripts/upstall-carthage.sh
  - ./scripts/upstall-swiftlint.sh

script:
- set -o pipefail && xcodebuild -scheme SwiftyTextTable -project SwiftyTextTable.xcodeproj clean build test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
